name: "Step 2: Publish Release"
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The target branch"
        required: false
      release_url:
        description: "The URL of the draft GitHub release"
        required: false
      steps_to_skip:
        description: "Comma separated list of steps to skip"
        required: false

jobs:
  publish_release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: jupyter-server/jupyter-releaser/.github/actions/common@v2

      - name: Populate Release
        id: populate-release
        uses: jupyter-server/jupyter-releaser/.github/actions/populate-release@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          target: ${{ github.repository }}
          branch: ${{ github.event.inputs.branch }}
          release_url: ${{ github.event.inputs.release_url }}
          steps_to_skip: ${{ github.event.inputs.steps_to_skip }}

      - name: Finalize Release
        id: finalize-release
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          TWINE_USERNAME: __token__
        uses: jupyter-server/jupyter-releaser/.github/actions/finalize-release@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          target: ${{ github.repository }}
          release_url: ${{ steps.populate-release.outputs.release_url }}

      - name: "** Next Step **"
        if: ${{ success() }}
        run: |
          echo "Verify the final release"
          echo ${{ steps.finalize-release.outputs.release_url }}
          echo "## Next Step" >> $GITHUB_STEP_SUMMARY
          echo "Verify the final release" >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.finalize-release.outputs.release_url }} >> $GITHUB_STEP_SUMMARY
          if [ ! -z "${{ steps.finalize-release.outputs.pr_url }}" ]; then
             echo "Merge the forwardport PR"
             echo ${{ steps.finalize-release.outputs.pr_url }}
             echo "Merge the forwardport PR" >> $GITHUB_STEP_SUMMARY
             echo ${{ steps.finalize-release.outputs.pr_url }} >> $GITHUB_STEP_SUMMARY
          fi

      - name: "** Failure Message **"
        if: ${{ failure() }}
        run: |
          echo "Failed to Publish the Draft Release Url:"
          echo ${{ steps.populate-release.outputs.release_url }}
          echo "## Failure Message" >> $GITHUB_STEP_SUMMARY
          echo ":x: Failed to Publish the Draft Release Url:" >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.populate-release.outputs.release_url }} >> $GITHUB_STEP_SUMMARY
          echo "Fix credentials and run 'Publish Release' workflow again" >> $GITHUB_STEP_SUMMARY
